// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9s-MnDcfYQ5jXPtxrwy08xPpeYyttFIk',
    appId: '1:417787636663:web:a45ba709c270d948ee1632',
    messagingSenderId: '417787636663',
    projectId: 'flash-chat-dd742',
    authDomain: 'flash-chat-dd742.firebaseapp.com',
    storageBucket: 'flash-chat-dd742.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6bpRyVIhugWkc0Ob5sxQpj-GvgQ2FiG0',
    appId: '1:417787636663:android:4d50b399830f57c2ee1632',
    messagingSenderId: '417787636663',
    projectId: 'flash-chat-dd742',
    storageBucket: 'flash-chat-dd742.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA19EeayEaL2yC4HzaP89haCxiJung3XI8',
    appId: '1:417787636663:ios:8854aaccae37e7eaee1632',
    messagingSenderId: '417787636663',
    projectId: 'flash-chat-dd742',
    storageBucket: 'flash-chat-dd742.firebasestorage.app',
    iosBundleId: 'com.example.sissifit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA19EeayEaL2yC4HzaP89haCxiJung3XI8',
    appId: '1:417787636663:ios:8854aaccae37e7eaee1632',
    messagingSenderId: '417787636663',
    projectId: 'flash-chat-dd742',
    storageBucket: 'flash-chat-dd742.firebasestorage.app',
    iosBundleId: 'com.example.sissifit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9s-MnDcfYQ5jXPtxrwy08xPpeYyttFIk',
    appId: '1:417787636663:web:016c94f3293ad0cbee1632',
    messagingSenderId: '417787636663',
    projectId: 'flash-chat-dd742',
    authDomain: 'flash-chat-dd742.firebaseapp.com',
    storageBucket: 'flash-chat-dd742.firebasestorage.app',
  );
}
